### ISSUE TITLE
No Thing

### ISSUE THREAD

**Issue by wang89280** [yewzijian/RegTR#24]

**Comment by yewzijian** [comment]
Hi, I’m not sure what you mean. If you found mistakes in the dependencies
do let me know so we can fix it, thanks.

**Comment by wang89280** [comment]
I'm very sorry, it's my mistake. 

I am currently experiencing some problems with my installation environment. The error message is as follows, please help me see how to solve it. 

The error is as follows:
```
Traceback (most recent call last):
  File "demo.py", line 22, in <module>
    from models.regtr import RegTR
  File "/home/wk/RegTR/RegTR/src/models/__init__.py", line 21, in <module>
    add_models(os.path.splitext(fname)[0])
  File "/home/wk/RegTR/RegTR/src/models/__init__.py", line 12, in add_models
    clsmembers = inspect.getmembers(importlib.import_module(f'models.{fname}'),
  File "/home/wk/anaconda3/envs/RegTR/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/wk/RegTR/RegTR/src/models/regtr.py", line 9, in <module>
    from models.generic_reg_model import GenericRegModel
  File "/home/wk/RegTR/RegTR/src/models/generic_reg_model.py", line 8, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/wk/anaconda3/envs/RegTR/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```

Looking forward to your reply！
